apiVersion: migration.openshift.io/v1alpha1
kind: MigCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migcluster-remote
  namespace: openshift-migration
spec:
  # [!] Change isHostCluster to 'true' if you'll be running the controller on this cluster.
  #     Setting 'isHostCluster' to true will bypass using the clusterRef and serviceAccountSecretRef below.
  isHostCluster: false

  url: "https://my-remote-cluster-ip.nip.io:8443"

  serviceAccountSecretRef:
    name: sa-token-remote
    namespace: openshift-migration
